CREATE TABLE IF NOT EXISTS tasks (
    "taskId" SERIAL PRIMARY KEY,
    "taskName" VARCHAR(255) NOT NULL,
    "taskDesc" VARCHAR(1500) NOT NULL,
    "complete" BOOLEAN NOT NULL DEFAULT false,
    "lastCompleted" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "repeatIntervHours" INTEGER NOT NULL DEFAULT 24
);