CREATE TABLE IF NOT EXISTS `tasks` (
  `taskId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `taskName` VARCHAR(255) NOT NULL,
  `complete` BOOLEAN NOT NULL DEFAULT 0,
  `lastCompleted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `repeatIntervHours` INT UNSIGNED NOT NULL DEFAULT 24,
  
  PRIMARY KEY (`taskId`)
);