// Package docs holds the generated v2 API contract.
//
// openapi.json is generated by `make spec` and committed. Embedding it means
// the running binary always serves exactly the contract it was built from,
// with no runtime file dependency to copy into the container image.
package docs

import _ "embed"

// OpenAPISpec is the OpenAPI 3.0 document describing the v2 API.
//
//go:embed openapi.json
var OpenAPISpec []byte
